In [2]:
import pandas as pd

In [40]:
h = {"Height" : [125,173,154,178,159] , "Weight" : [100, 95, 85, 80, 77]}
# Has to be in a format tht the model can understand, It has to have rows and columns

In [41]:
df = pd.DataFrame(h)
print(df)


   Height  Weight
0     125     100
1     173      95
2     154      85
3     178      80
4     159      77


In [42]:
h2 = {"Brain" : {"height" : 125, "weight" : 100},
     "Lakes" :{"height" : 125, "weight" : 100},
     "James" :{"height" : 125, "weight" : 100},
     "Trump" :{"height" : 125, "weight" : 100},
     "Bite" :{"height" : 125, "weight" : 100}}

In [43]:
df2 = pd.DataFrame(h2)
df2

,Brain,Lakes,James,Trump,Bite
height,125,125,125,125,125
weight,100,100,100,100,100


In [44]:
df3 = pd.DataFrame.from_dict(h2, orient="index")
df3

,height,weight
Brain,125,100
Lakes,125,100
James,125,100
Trump,125,100
Bite,125,100


In [45]:
#Add a column 
df["Gender"] = ["M", "F", "F", "M", "F"]
df["City"] = ["PTA", "KZN", "CPT", "FST", "DBN"]
df

,Height,Weight,Gender,City
0,125,100,M,PTA
1,173,95,F,KZN
2,154,85,F,CPT
3,178,80,M,FST
4,159,77,F,DBN


In [46]:
#Add a row
df.loc[5] = [166, 101, "F", "PTA"]
df


,Height,Weight,Gender,City
0,125,100,M,PTA
1,173,95,F,KZN
2,154,85,F,CPT
3,178,80,M,FST
4,159,77,F,DBN
5,166,101,F,PTA


In [47]:
#To add a dataframe to a dataframe it has to be the same type of dataframe 
#Has to match the second dataframe to the new one 

#df = pd.concat({df, added_df], ignore_index=True)


In [48]:
#Rename a column 
#inplace = True makes it permanent
df.rename(columns = {"City" : "City_Code"}, inplace=True)

In [49]:
df

,Height,Weight,Gender,City_Code
0,125,100,M,PTA
1,173,95,F,KZN
2,154,85,F,CPT
3,178,80,M,FST
4,159,77,F,DBN
5,166,101,F,PTA


In [50]:
#Save a file
df.to_csv("age_data.csv", index=False)

In [51]:
import sqlite3

In [52]:
connection = sqlite3.connect("student_record.db")
#An empty database will be created that we can use it. And we also need to close the database 

In [53]:
#Creating objectz

cursor = connection.cursor()

In [54]:
#Use queries 
cursor.execute("create table student (studnet_name text, gender text, age integer, department text)")

In [55]:
student_details = [("Magi", "F", 24, "CS"),
                   ("James", "M", 29, "ICT"),
                   ("Pius", "M", 19, "ACCT"),
                   ("Castro", "M", 26, "CivENG"),
                   ("Dan", "M", 25, "CS")]
                   

In [56]:
cursor.executemany("insert into student values(?,?,?,?)", student_details)
#Inserting into the table we have in the database 
# ? is a placeholder 


In [57]:
#
connection.commit()

In [61]:
for row in cursor.execute("select * from student"):
    print(row)

ProgrammingError: Cannot operate on a closed database.

In [59]:
connection.close()

In [60]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [ ]:
#Read or Load  a Database 
#Import SQLite3 
#Import Pandas as pd


In [63]:
connection = sqlite3.connect("student_record.db")
# tO connect to the database opening the database 

In [66]:
#Read method to read the table not the database 
#Now we access the table in the database
df_db = pd.read_sql("select * from student", connection)
#veiw the database 

df_db

,studnet_name,gender,age,department
0,Magi,F,24,CS
1,James,M,29,ICT
2,Pius,M,19,ACCT
3,Castro,M,26,CivENG
4,Dan,M,25,CS


In [67]:
connection.close()

In [69]:
#reading the csv file where we dont have to open a new connection 

df_new = pd.read_csv("age_data.csv")
df_new

,Height,Weight,Gender,City_Code
0,125,100,M,PTA
1,173,95,F,KZN
2,154,85,F,CPT
3,178,80,M,FST
4,159,77,F,DBN
5,166,101,F,PTA


In [70]:
#View first couple or last couple rows of the dataset 
df_new.head()

,Height,Weight,Gender,City_Code
0,125,100,M,PTA
1,173,95,F,KZN
2,154,85,F,CPT
3,178,80,M,FST
4,159,77,F,DBN


In [71]:
df_new.tail()

,Height,Weight,Gender,City_Code
1,173,95,F,KZN
2,154,85,F,CPT
3,178,80,M,FST
4,159,77,F,DBN
5,166,101,F,PTA


In [72]:
df_column = df_new["Height"]
df_column


0    125
1    173
2    154
3    178
4    159
5    166
Name: Height, dtype: int64

In [73]:

#specific column 
df_cloumn = df_new["Height"][2]
df_column 

0    125
1    173
2    154
3    178
4    159
5    166
Name: Height, dtype: int64

In [74]:
print(df_column)

0    125
1    173
2    154
3    178
4    159
5    166
Name: Height, dtype: int64


In [76]:
df_column = df_new[["Height", "Weight"]]
df_column

,Height,Weight
0,125,100
1,173,95
2,154,85
3,178,80
4,159,77
5,166,101


In [77]:
df_row = df_new.iloc[1]
print(df_row)

Height       173
Weight        95
Gender         F
City_Code    KZN
Name: 1, dtype: object


In [79]:
#range of rows 
df_row = df_new.iloc[1:3]
print(df_row)

   Height  Weight Gender City_Code
1     173      95      F       KZN
2     154      85      F       CPT


In [81]:
#retrive a specific cell
df_cell = df_new.iloc[1]["Weight"]
print(df_cell)

95


In [82]:
#using opperators witht the dataframe 
#double the height 

df_new["height_double"] =  df_new["Height"] * 2
df_new

,Height,Weight,Gender,City_Code,height_double
0,125,100,M,PTA,250
1,173,95,F,KZN,346
2,154,85,F,CPT,308
3,178,80,M,FST,356
4,159,77,F,DBN,318
5,166,101,F,PTA,332


In [85]:
#divide height by the weight
df_new["half_height_by_weight"] = df_new["Height"] / df_new["Weight"]
df_new

,Height,Weight,Gender,City_Code,height_double,half_weight_by_height,half_height_by_weight
0,125,100,M,PTA,250,1.250000,1.250000
1,173,95,F,KZN,346,1.821053,1.821053
2,154,85,F,CPT,308,1.811765,1.811765
3,178,80,M,FST,356,2.225000,2.225000
4,159,77,F,DBN,318,2.064935,2.064935
5,166,101,F,PTA,332,1.643564,1.643564


In [87]:
new_height = []

for i in range(len(df_new)):
    n_height = df_new["Height"][i] + 5
    new_height.append(n_height)

df_new["Growth"] = new_height
df_new

,Height,Weight,Gender,City_Code,height_double,half_weight_by_height,half_height_by_weight,Growth
0,125,100,M,PTA,250,1.250000,1.250000,130
1,173,95,F,KZN,346,1.821053,1.821053,178
2,154,85,F,CPT,308,1.811765,1.811765,159
3,178,80,M,FST,356,2.225000,2.225000,183
4,159,77,F,DBN,318,2.064935,2.064935,164
5,166,101,F,PTA,332,1.643564,1.643564,171


In [89]:
df_m = df_new.replace("KZN","DBN")
df_m

,Height,Weight,Gender,City_Code,height_double,half_weight_by_height,half_height_by_weight,Growth
0,125,100,M,PTA,250,1.250000,1.250000,130
1,173,95,F,DBN,346,1.821053,1.821053,178
2,154,85,F,CPT,308,1.811765,1.811765,159
3,178,80,M,FST,356,2.225000,2.225000,183
4,159,77,F,DBN,318,2.064935,2.064935,164
5,166,101,F,PTA,332,1.643564,1.643564,171


In [3]:
import pandas as pd

In [4]:
df_new = pd.read_csv("age_data.csv")

In [5]:
df_new.head(3)

,Height,Weight,Gender,City_Code
0,125,100,M,PTA
1,173,95,F,KZN
2,154,85,F,CPT


In [8]:
df_m = df_new.drop("Weight", axis=1)
df_m

,Height,Gender,City_Code
0,125,M,PTA
1,173,F,KZN
2,154,F,CPT
3,178,M,FST
4,159,F,DBN
5,166,F,PTA


In [15]:
df_new.drop(["Height", "Gender"], axis=1, inplace=True)
#drop a column 

In [18]:
#Arrays

import numpy as np 

In [13]:
arr_empt = np.zeros((3, 3))

In [14]:
arr_empt

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr_empt_1 = np.ones((4, 4))
arr_empt_1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
arr_empt_1[1][1] = 4 
arr_empt_1

array([[1., 1., 1., 1.],
       [1., 4., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
#One dimentional array 

arr_1 = np.arange(10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr_1 = np.arange(2,10)
arr_1


array([2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#include numbers in intervals 
arr_1 = np.arange(0,10, 2)
arr_1

array([0, 2, 4, 6, 8])

In [32]:
#list to array 

list = [12, 23, 11, 9, 87, 12, 34, 12]

arr_list = np.array(list)
arr_list

array([12, 23, 11,  9, 87, 12, 34, 12])

In [33]:
#Multidimentional Arrays 

arr_2 = np.array((np.arange(3,15,2), np.arange(4,16,2)))
arr_2

array([[ 3,  5,  7,  9, 11, 13],
       [ 4,  6,  8, 10, 12, 14]])

In [34]:
print(arr_1)

[0 2 4 6 8]


In [35]:
print(arr_2)

[[ 3  5  7  9 11 13]
 [ 4  6  8 10 12 14]]


In [36]:
print(arr_1.shape)
print(arr_2.shape)

(5,)
(2, 6)


In [37]:
#re shape a array 

arr_3 = arr_2.reshape(6,2)
arr_3

array([[ 3,  5],
       [ 7,  9],
       [11, 13],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [42]:
arr_2 = np.array([[2,5,2], [1,9,3], [8,3,5]])
arr_2

array([[2, 5, 2],
       [1, 9, 3],
       [8, 3, 5]])

In [43]:
arr_2[2] = 6
arr_2


array([[2, 5, 2],
       [1, 9, 3],
       [6, 6, 6]])

In [44]:
arr_2[2][0] = 8
arr_2[2][1] = 3
arr_2[2][2] = 5

arr_2

array([[2, 5, 2],
       [1, 9, 3],
       [8, 3, 5]])

In [45]:
arr_2[arr_2 == 5] = 6

In [46]:
arr_2

array([[2, 6, 2],
       [1, 9, 3],
       [8, 3, 6]])

In [47]:
arr_2[2:, 1:]

array([[3, 6]])

In [48]:
arr_2[1:, 1:]

array([[9, 3],
       [3, 6]])

In [52]:
#sort array 

arr_temp = np.sort(arr_2, axis=0, kind="mergesort", )
arr_temp

array([[1, 3, 2],
       [2, 6, 3],
       [8, 9, 6]])

In [53]:

#it just uses the same memory not making new_arr a copy 
#new_arr = arr_2
new_arr = arr_2.copy()